DROP DATABASE IF EXISTS conio CASCADE;
CREATE DATABASE IF NOT EXISTS conio;
SET DATABASE = conio;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL NOT NULL PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL UNIQUE
);